use clap::{Arg, Command, crate_description, crate_name, crate_version, value_parser};

pub(crate) fn build_cmd() -> Command {
    Command::new(crate_name!())
        .about(crate_description!())
        .version(crate_version!())
        .subcommand(Command::new("gui").about("Launch the GUI"))
        .subcommand(
            Command::new("img").about("Create a map image")
                .arg(Arg::new("seed")
                    .help("Seed as unsigned 64-bit integer")
                    .value_parser(value_parser!(u64))
                    .required(true)
                )
                .arg(Arg::new("tile-size")
                    .help("Size of tile in pixels")
                    .long("tile-size")
                    .value_parser(value_parser!(usize))
                    .default_value("128")
                )
                .arg(Arg::new("tiles")
                    .help("Amount of tiles per side")
                    .long("tiles")
                    .value_parser(value_parser!(i32))
                    .default_value("1")
                )
                .arg(Arg::new("sample-height")
                    .help("Height / y-level at which to sample the biomes at. If you sample lower you will see cave biomes")
                    .long("sample-height")
                    .short('y')
                    .short_alias('y')
                    .value_parser(value_parser!(i32))
                    .default_value("256")
                )
                .arg(Arg::new("scale")
                    .long("scale")
                    .help("Scale in powers of two. 0 means each pixel represents one quart (4x4 blocks), 1 -> 8x8 blocks per pixel, 2 -> 16x16 blocks per pixel etc.")
                    .allow_negative_numbers(false)
                    .value_parser(value_parser!(u8).range(0..=16))
                    .default_value("0")
            )
        )
}
